### ISSUE TITLE
SCSP via Pre-Commit

### ISSUE THREAD

**Issue by bmorrissirromb** [awslabs/simple-code-scanning-pipeline#32]
Implementing the pipeline through Pre-Commit would allow for de-duplicating client and server side scanning configuration.

Example pre-commit configuration:
```yaml
repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.1.266
    hooks:
      - id: checkov

  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.4
    hooks:
    -  id: bandit
       # args: [--skip, "B101", --recursive, .] 

  - repo: https://github.com/awslabs/git-secrets
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
    - id: git-secrets
      entry: git-secrets --scan
      files: .
      args: [--untracked]
```

And then run `pre-commit run --all-files` in the pipeline.

The reporting would need some refactoring, but this could be a really neat way to standardize and make the tool more repo-agnostic.
